import { IconType } from "react-icons";

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiOutlineArrowPath,
  HiCheck,
  HiOutlineSun,
  HiOutlineMoon,
  HiMiniQuestionMarkCircle,
  HiMiniMinus,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiMiniPlus,
  HiMiniUser,
  HiMiniXMark,
  HiEyeDropper,
  HiOutlineClipboard,
  HiOutlineMagnifyingGlass,
  HiCalendar,
  HiOutlineLink,
  HiExclamationTriangle,
  HiArrowUpRight,
  HiInformationCircle,
  HiExclamationCircle,
  HiCheckCircle,
  HiOutlineShieldCheck,
  HiOutlineSparkles,
  HiMiniGlobeAsiaAustralia,
} from "react-icons/hi2";

import { PiBookBookmark, PiCoffee, PiHourglass, PiHouseDuotone, PiLegoSmiley, PiLinkedinLogo, PiTag, PiThumbsUp } from "react-icons/pi";

import { RiVisaLine } from "react-icons/ri";

import { FaAws, FaDiscord, FaDocker, FaGithub, FaGolang, FaGoogle } from "react-icons/fa6";
import { SiRubyonrails } from "react-icons/si";
import { TbBrandNextjs, TbBrandTailwind } from "react-icons/tb";
import { FaDigitalOcean, FaLinux } from "react-icons/fa";
import { BiLogoPostgresql } from "react-icons/bi";

export const iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  check: HiCheck,
  light: HiOutlineSun,
  dark: HiOutlineMoon,
  helpCircle: HiMiniQuestionMarkCircle,
  infoCircle: HiInformationCircle,
  warningTriangle: HiExclamationTriangle,
  errorCircle: HiExclamationCircle,
  checkCircle: HiCheckCircle,
  eyeDropper: HiEyeDropper,
  clipboard: HiOutlineClipboard,
  person: HiMiniUser,
  close: HiMiniXMark,
  openLink: HiOutlineLink,
  discord: FaDiscord,
  google: FaGoogle,
  github: FaGithub,
  arrowUpRight: HiArrowUpRight,
  minus: HiMiniMinus,
  plus: HiMiniPlus,
  calendar: HiCalendar,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  search: HiOutlineMagnifyingGlass,
  visa: RiVisaLine,
  security: HiOutlineShieldCheck,
  sparkle: HiOutlineSparkles,
  home: PiHouseDuotone,
  globe: HiMiniGlobeAsiaAustralia,
  book: PiBookBookmark,
  lego: PiLegoSmiley,
  like: PiThumbsUp,
  tag: PiTag,
  glasses: PiHourglass,
  linkedin: PiLinkedinLogo,
  rails: SiRubyonrails,
  golang: FaGolang,
  nextjs: TbBrandNextjs,
  tailwind: TbBrandTailwind,
  docker: FaDocker,
  coffee: PiCoffee,
  aws: FaAws,
  linux: FaLinux,
  digitalocean: FaDigitalOcean,
  postgresql: BiLogoPostgresql,
};
